### ISSUE TITLE
I'd like to give pease a chance

### ISSUE THREAD

**Issue by gustavofranke** [pease/pease#1]
Hi, wanted to try out your library but grape complains saying 

Invalid import definition: 'pease.gherkin.FeatureLoader'; reason: startup failed:
script14395570832031847087532.groovy: 1: unable to resolve class pease.gherkin.FeatureLoader
 @ line 1, column 1.
   import pease.gherkin.FeatureLoader
   ^

1 error

Invalid import definition: 'pease.groovy.StepLoader'; reason: startup failed:
script143955708327428121266.groovy: 1: unable to resolve class pease.groovy.StepLoader
 @ line 1, column 1.
   import pease.groovy.StepLoader
   ^

1 error

Invalid import definition: 'pease.Configuration'; reason: startup failed:
script1439557083281950938341.groovy: 1: unable to resolve class pease.Configuration
 @ line 1, column 1.
   import pease.Configuration
   ^

1 error

General error during conversion: Error grabbing Grapes -- [unresolved dependency: gherkin#gherkin;2.4.16: not found]

**Comment by gustavofranke** [comment]
Then went on issuing grape -V resolve com.github.pease pease 0.1.0, but to no avail

**Comment by gustavofranke** [comment]
And after cloning the repo and following the steps stated in the README.md gradle has thrown 
        ::::::::::::::::::::::::::::::::::::::::::::::

```
    ::          UNRESOLVED DEPENDENCIES         ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: gherkin#gherkin;2.4.16: not found

    ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by JanAhrens** [comment]
Hi @gustavofranke,

Thanks for reporting your problems with pease. I didn't saw your ticket ealier. Apologies for that.

I guess you already figured out that this project got abandoned. I left it here for people to read and learn. Maybe I should make this more obvious in the README files.

Kudos for the great issue name :smile: 

Cheers, Jan

**Comment by JanAhrens** [comment]
I marked the projects as unmaintained and created a post [on the webpage](http://pease.github.io/2015/10/06/unmaintained.html). Great that you took the time to give it a try. I hope that you found a better alternative :smiley:
